dad

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -6,9 +6,6 @@ modified_files=$(git diff --cached --name-only --diff-filter=AM -- '*.java')
 # Run PMD on the modified files
 if [ -n "$modified_files" ]; then
     ./libs/pmd-bin-6.52.0/bin/run.sh pmd -d "$modified_files" -R pmd/rules.xml -f text | awk '{ print NR ": " $0 }'
-fi
-
-if [ $? -ne 0 ]; then
-  echo "PMD found errors, cancelling commit"
-  exit 1
+    echo -e "\033[31mPMD found errors, cancelling commit! Please fix first!\033[0m"
+    exit 1
 fi
